// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayerManagementService.Data;

#nullable disable

namespace PlayerManagementService.Migrations
{
    [DbContext(typeof(PlayerContext))]
    [Migration("20241209041157_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayerManagementService.Model.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("isDrafted")
                        .HasColumnType("bit");

                    b.HasKey("PlayerId");

                    b.ToTable("Player");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            Name = "John Go",
                            Position = "Front Guard",
                            TeamId = 1,
                            isDrafted = false
                        },
                        new
                        {
                            PlayerId = 2,
                            Name = "Alice Swift",
                            Position = "Center Forward",
                            TeamId = 1,
                            isDrafted = false
                        },
                        new
                        {
                            PlayerId = 3,
                            Name = "Bob Lee",
                            Position = "Point Guard",
                            TeamId = 2,
                            isDrafted = false
                        },
                        new
                        {
                            PlayerId = 4,
                            Name = "Tom Jones",
                            Position = "Point Guard",
                            TeamId = 2,
                            isDrafted = false
                        },
                        new
                        {
                            PlayerId = 5,
                            Name = "Samantha Green",
                            Position = "Shooting Guard",
                            TeamId = 2,
                            isDrafted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
